export const userStatusCode = {
    500: "Lỗi không xác định. Vui lòng thử lại sau",
    1001: "Người dùng được tìm thấy",
    1002: "Không tìm thấy người dùng",
    1003: "Đăng nhập thành công",
    1004: "Tên người dùng hoặc mật khẩu không hợp lệ",
    1005: "Đầu vào không hợp lệ",
    1006: "Người dùng đã tồn tại",
    1007: "Đăng ký thành công. Vui lòng kiểm tra email để xác nhận đăng ký",
    1008: "Không thể tạo người dùng",
    1009: "Không thể gửi mã xác minh qua email",
    1010: "Tài khoản đã được xác minh thành công",
    1011: "Mã xác minh không hợp lệ",
    1012: "Gửi mã thành công",
    1013: "Đặt lại mật khẩu thành công",
    1014: "Cập nhật mật khẩu thành công",
    1015: "Mật khẩu cũ không hợp lệ",
    1016: "Cập nhật hồ sơ thành công",
    1017: "Người dùng không hợp lệ",
    1018: "Vui lòng xác minh tài khoản của bạn trước",
    1019: "Tài khoản của bạn đã bị vô hiệu hóa",
};
